### ISSUE TITLE
ci: add caching to lint

### ISSUE THREAD

**Issue by teaishealthy** [eludris-community/eludris_flutter#21]
:rocket:

**Comment by amoghrajesh** [comment]
@teaishealthy can you be more elaborate here? I would be interested in this issue

**Comment by teaishealthy** [comment]
> @teaishealthy can you be more elaborate here? I would be interested in this issue

@amoghrajesh someone is already working on this in #22

**Comment by teaishealthy** [comment]
@amoghrajesh You can work on this!

**Comment by teaishealthy** [comment]
Also from the closed PR
> Hey!
I could have probably been more descriptive in the issue, but by "lint" I meant the GitHub Workflow, which unlike the "build" workflow does not have any caching.

**Comment by spifory** [comment]
Can I work on this?
