### ISSUE TITLE
Dissallow names less than 2 characters long or more than 32 characters 

### ISSUE THREAD

**Issue by EnokiUN** [eludris-community/eludris_flutter#49]

**Comment by teaishealthy** [comment]
Show a Snackbar (toast message) after pressing the connect button or disable the button until more than two characters have been typed?

**Comment by EnokiUN** [comment]
> Show a Snackbar (toast message) after pressing the connect button or disable the button until more than two characters have been typed?

disable + some sort of hint

**Comment by SichangiFelix** [comment]
Hi, I would like to work on this.

**Comment by EnokiUN** [comment]
> Hi, I would like to work on this.

Great! I've updated the issue too to be more correct

**Comment by SichangiFelix** [comment]
I have completed the task and created a PR.

**Comment by EnokiUN** [comment]
#56
